version: '3'

services:
  cetelem-simulator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app

volumes:
  data:
